### ISSUE TITLE
Add dependency on coffee-rails

### ISSUE THREAD

**Issue by andrewdsmith** [turbolinks/turbolinks-rails#22]
I recently removed the coffee-rails gem from my Rails app Gemfile as a bit of housekeeping as I was not using CoffeeScript anywhere directly. What I didn't notice at the time was that the turbolinks 2.2 gem still depended on coffee-rails and so everything kept working fine.

When I updated turbolinks from 2.5 to 5.0 it broke the app because coffee-rails was no longer present. Some time between 2.5 and 5.0 the gem dependency on coffee-rails was removed.

It would seem sensible to add it back here to prevent other obsessive-compulsive dependency cleaners like myself from tripping up on this.

**Comment by andrewdsmith** [comment]
For the record, basing my assertion above on this diff of my Gemfile.lock:

```
diff --git a/Gemfile.lock b/Gemfile.lock
index 069dea6..e243130 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -238,8 +238,9 @@ GEM
     thor (0.20.0)
     thread_safe (0.3.6)
     tilt (2.0.8)
-    turbolinks (2.5.3)
-      coffee-rails
+    turbolinks (5.0.1)
+      turbolinks-source (~> 5)
+    turbolinks-source (5.0.3)
     twitter-typeahead-rails (0.11.1)
       actionpack (>= 3.1)
       jquery-rails
```

**Comment by ypresto** [comment]
IMO you should put what you depend on to Gemfile by yourself, not by library.

**Comment by javan** [comment]
Turbolinks 5+ does not depend on CoffeeScript for its Rails integration
