### ISSUE TITLE
redirect_to with turbolinks option failing

### ISSUE THREAD

**Issue by ghost** [turbolinks/turbolinks-rails#7]
I have an issue with cross domain redirects and Turbolinks not working as expected. Although I should admit at this point that this expectation is set using the README on [turbolinks/turbolinks-classic](https://github.com/turbolinks/turbolinks-classic) since this repo doesn't have one. :]

If I add `'data-turbolinks' => false` to the HTML link that triggers a redirect, then the redirection happens fine and no errors are printed to the JavaScript console. However, if I remove that data tag, and instead add the `turbolinks: false` option to the `redirect_to` call, then I get the initial XHR request, followed by the `No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin ... is therefore not allowed access.` error printed to the JavaScript console, followed by the HTML redirection request, which then succeeds.

I was under the impression that adding `turbolinks: false` to a `redirect_to` call would cause the browser to redirect normally, and therefore no `Access-Control-Allow-Origin` error would be printed to the log.
### A little more context

We have an SSO service that all our apps communicate with. Each app has both a prominent sign on/off link, as well as automatic sign in if a user is already signed in to one of the other apps using the service. Adding the `data-turbolinks` tag to the links works fine, but it's the automatic sign in that is generating the `Access-Control-Allow-Origin` error. The way this works is that some business logic runs in a `before_action` in the application controller, and if it's determined that a user can be automatically signed in then a redirect happens using `redirect_to` to our SSO service that is hosted on a different domain.
### Steps to reproduce

You can recreate the behaviour I'm seeing with this very simple example:

``` ruby
# controller.rb
class Controller < ApplicationController
  def google
    redirect_to('http://google.com', turbolinks: false)
  end
end

# routes.rb
get 'google', to: 'sessions#google'

# index.html.erb
<%= link_to("Google", google_path) %>
```
### Expected behavior

The response served to the browser would cause it to redirect normally and not attempt to load the contents of the redirection via XHR.
### Actual behavior

An attempt to redirect via XHR is triggered, followed by...

```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin ... is therefore not allowed access.
```

...followed by a normal redirection.
### System configuration

**Rails version**: Rails 5.0.0.beta3

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by jeremy** [comment]
From the README:

> Note: in v3.0, the default behavior of redirect_to is to redirect via Turbolinks on XHR + non-GET requests. You can opt-out of this behavior by passing turbolinks: false to redirect_to.

Passing `turbolinks: false` means "return 302 Found to the XHR request" not "redirect the browser location to the new URL as if this hadn't been an XHR request in the first place." If that makes sense 😊

That's why `'data-turbolinks' => false` works as you expect. It means you get a browser page load, not an XHR page load, so a 302 Found response does redirect the browser window, not the XHR response.

**Comment by ghost** [comment]
> the default behavior of redirect_to is to redirect via Turbolinks on XHR + non-GET requests

This is still a bit confusing as it implies XHR + GET requests **wouldn't** redirect via Turbolinks.

In the example I've given passing `true` _or_ passing `false` yield the same result.

Could you advise on how best to handle cross domain server side redirection on a Turbolinks initiated XHR + GET request?

**Comment by adrianthedev** [comment]
I have encountered this issue as well and need to set the redirection server-side.
