### ISSUE TITLE
5.0.0.beta2 / redirect_to with turbolinks action 'change' renders {"action":"replace"} instead of { change: [...] }

### ISSUE THREAD

**Issue by doerfli** [turbolinks/turbolinks-rails#8]
### Steps to reproduce

I have this view with turbolinks and would like to have a partial update of the div `#result` through serverside turbolinks. 

```
<div id="result" data-turbolinks-temporary>
  <% if flash[:new] %>
      Created new mock. Send your requests to <%= link_to flash[:new] %>.
  <% end %>
</div>
<div>
  <%= form_for @new_mock, :remote => true do |f| %>
      <%= f.label :statuscode %>:
      <%= f.text_field :statuscode %><br />
...
      <%= f.submit %>
  <% end %>
</div>
```

And its backed by this controller 

```
class MocksController < ApplicationController

  def index
    @new_mock = Mock.new
  end

  def create
    mock = Mock.new(mock_params)
    mock.save
    flash[:new] = mock

    redirect_to mocks_path, change: ['result']
  end

  private
...
end
```
### Expected behavior

When submitting the form, i would expect the response of the POST to be 

```
Turbolinks.clearCache()
Turbolinks.visit("http://localhost:3000/mocks", { change: ['result'] })
```
### Actual behavior

But i get

```
Turbolinks.clearCache()
Turbolinks.visit("http://localhost:3000/mocks", {"action":"replace"})
```
### System configuration

**Rails version**: 5.0.0.beta4
**Turbolinks-rails version**: 5.0.0.beta2

**Ruby version**: 2.3.0

**Comment by dsander** [comment]
@doerfli partial replacement was [removed from turbolinks 5](https://github.com/turbolinks/turbolinks/wiki/Turbolinks-5-FAQ#why-did-you-remove-partial-replacement)
